# Welcome to Durexp Config File
# Here you will find the default config settings feel free to change them to suit your liking! :)
# If you have any problems please create a ticket:
# http://dev.bukkit.org/bukkit-plugins/double-your-experience/tickets/
#     #
# AutoUpdate: True
#     # true = automatically update this plugin when a new version is released.
#     # false = ignore updates
# EnableVotifer: True - In the Works
#     # true = Enables you to give rewards for voting
#     # false = disables rewards for voting
# Enable: true
#     # true = enable plugin
#     # false = disable plugin
#     # in-game command:
#     # /durexp toggle
# Multiplier: 2.0
#     # This will allow you to set a server wide Multiplier
#     # This number is ignored if EnablePermMultiplier = true
# EnablePermMultiplier: false
#     # true = Instead of one server-wide-"Multiplier",
#     # there will be a different "Multiplier" for each permission node that you create.
#     # Give this permission node to a player or a group: (max = 10.0)
#     # doubleurexp.multiplier.<number>
# DaysToEnable:
#     # This is a list of the days that are enabled, 
#     # shown is the different ways you can write the date, 
#     # the plugin will detect them all!!!
# CheckForSpawner: true
#     # Enables/disables the check for mob spawners.
#     # true = check for nearby mob spawners before giving bonus experience.
#     # false = do not check for nearby mob spawners: just give out bonus xp.
# CheckRadius: 40
#     # The radius that the plugin will check if the "CheckForSpawner" option is enabled, 
#     # could be used to prevent mass farming. <---We don't want that now!
#     # The radius that the plugin will check if the "CheckForSpawner" option is enabled, 
#     # could be used to prevent mass farming. <---We don't want that now!
# DaysToEnable:
#     # This is a list of the days that are enabled, 
#     # shown is the different ways you can write the date, 
#     # the plugin will detect them all!!!
# CheckForSpawner: true
#     # Enables/disables the check for mob spawners.
#     # true = check for nearby mob spawners before giving bonus experience.
#     # false = do not check for nearby mob spawners: just give out bonus xp.
# CheckRadius: 40
AutoUpdate: true
# EnableVotifier: true
Enable: true
Multiplier: 2.0
EnablePermMultiplier: false
DaysToEnable:
- Monday
- tuesday
- wed
- thursday
- frida
- sat
- SundAy
CheckForSpawner: true
CheckRadius: 40
